# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'item_options_wizard.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ItemOptionsWizard(object):
    def setupUi(self, ItemOptionsWizard):
        ItemOptionsWizard.setObjectName("ItemOptionsWizard")
        ItemOptionsWizard.setWindowModality(QtCore.Qt.ApplicationModal)
        ItemOptionsWizard.resize(473, 253)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ItemOptionsWizard.sizePolicy().hasHeightForWidth())
        ItemOptionsWizard.setSizePolicy(sizePolicy)
        ItemOptionsWizard.setMinimumSize(QtCore.QSize(473, 253))
        ItemOptionsWizard.setMaximumSize(QtCore.QSize(16775, 16755))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/assets/icons/vendor.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ItemOptionsWizard.setWindowIcon(icon)
        ItemOptionsWizard.setSizeGripEnabled(False)
        ItemOptionsWizard.setModal(False)
        ItemOptionsWizard.setWizardStyle(QtWidgets.QWizard.ClassicStyle)
        ItemOptionsWizard.setOptions(QtWidgets.QWizard.IndependentPages|QtWidgets.QWizard.NoBackButtonOnStartPage)
        ItemOptionsWizard.currentId()
        self.wizard_start_page = QtWidgets.QWizardPage()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wizard_start_page.sizePolicy().hasHeightForWidth())
        self.wizard_start_page.setSizePolicy(sizePolicy)
        self.wizard_start_page.setMinimumSize(QtCore.QSize(342, 0))
        self.wizard_start_page.setMaximumSize(QtCore.QSize(342, 113))
        self.wizard_start_page.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.wizard_start_page.setObjectName("wizard_start_page")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.wizard_start_page)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.wizard_start_page_container = QtWidgets.QWidget(self.wizard_start_page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wizard_start_page_container.sizePolicy().hasHeightForWidth())
        self.wizard_start_page_container.setSizePolicy(sizePolicy)
        self.wizard_start_page_container.setStyleSheet("border-image: none;")
        self.wizard_start_page_container.setObjectName("wizard_start_page_container")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.wizard_start_page_container)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.wizard_start_page_options = QtWidgets.QWidget(self.wizard_start_page_container)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wizard_start_page_options.sizePolicy().hasHeightForWidth())
        self.wizard_start_page_options.setSizePolicy(sizePolicy)
        self.wizard_start_page_options.setObjectName("wizard_start_page_options")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.wizard_start_page_options)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.wizard_start_project_name = QtWidgets.QWidget(self.wizard_start_page_options)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wizard_start_project_name.sizePolicy().hasHeightForWidth())
        self.wizard_start_project_name.setSizePolicy(sizePolicy)
        self.wizard_start_project_name.setObjectName("wizard_start_project_name")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.wizard_start_project_name)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(6)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.project_name_label = QtWidgets.QLabel(self.wizard_start_project_name)
        self.project_name_label.setObjectName("project_name_label")
        self.horizontalLayout.addWidget(self.project_name_label)
        self.project_name_input = QtWidgets.QLineEdit(self.wizard_start_project_name)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.project_name_input.sizePolicy().hasHeightForWidth())
        self.project_name_input.setSizePolicy(sizePolicy)
        self.project_name_input.setFrame(True)
        self.project_name_input.setObjectName("project_name_input")
        self.horizontalLayout.addWidget(self.project_name_input)
        self.verticalLayout_2.addWidget(self.wizard_start_project_name)
        self.verticalLayout.addWidget(self.wizard_start_page_options)
        self.verticalLayout_3.addWidget(self.wizard_start_page_container)
        ItemOptionsWizard.addPage(self.wizard_start_page)
        self.wizard_base_groups_page = QtWidgets.QWizardPage()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wizard_base_groups_page.sizePolicy().hasHeightForWidth())
        self.wizard_base_groups_page.setSizePolicy(sizePolicy)
        self.wizard_base_groups_page.setMinimumSize(QtCore.QSize(452, 0))
        self.wizard_base_groups_page.setObjectName("wizard_base_groups_page")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.wizard_base_groups_page)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.base_group_btns = QtWidgets.QWidget(self.wizard_base_groups_page)
        self.base_group_btns.setMinimumSize(QtCore.QSize(400, 0))
        self.base_group_btns.setStyleSheet("QWidget {\n"
"border-image: none;\n"
"}\n"
"QPushButton {\n"
"                border: 1px solid #000;\n"
"                  border-top-width: 1px;\n"
"                   border-right-width: 1px;\n"
"                   border-bottom-width: 1px;\n"
"                   border-left-width: 1px;\n"
"                   border-top-style: solid;\n"
"                 border-right-style: solid;\n"
"                  border-bottom-style: solid;\n"
"                   border-left-style: solid;\n"
"                   border-top-color: rgb(0, 0, 0);\n"
"                  border-right-color: rgb(0, 0, 0);\n"
"                   border-bottom-color: rgb(0, 0, 0);\n"
"                   border-left-color: rgb(0, 0, 0);\n"
"                  border-image-source: initial;\n"
"                  border-image-slice: initial;\n"
"                  border-image-width: initial;\n"
"                  border-image-outset: initial;\n"
"                border-image-repeat: initial;\n"
"                border-radius: 4px;\n"
"                background-color: qlineargradient(x1: 0, y1: 1, x2: 0, y2: 0, stop: 0 #1e1e1e, stop: 1 #3c3c3c);\n"
"                border-image: none;\n"
"              color: #FFF;\n"
"               text-shadow: 1px 1px #000;\n"
"               box-shadow: inset 0 1px 1px #666, 0 1px 2px rgba(0,0,0,0.31);\n"
"                font-family: Open Sans;\n"
"                font-size: 12px;\n"
"               font-weight: bold;\n"
"               height: 36px;\n"
"                line-height: 36px;\n"
"                text-align: center;\n"
"                margin: 0px;\n"
"           }\n"
"            QPushButton::hover {\n"
"                background-color: qlineargradient(x1: 0, y1: 0, x2: 0 y2: 1,\n"
"                                                 stop: 0 #2d2d2d, stop: 1 #4b4b4b);\n"
"           }\n"
"            QPushButton::pressed {\n"
"                background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                                  stop: 0 #4b4b4b, stop: 1 #2d2d2d);\n"
"            }\n"
"            QPushButton::checked {\n"
"                background-color: qlineargradient(x1: 0, y1: 0, x2: 0 y2: 1,\n"
"                                                 stop: 0 #2d2d2d, stop: 1 #4b4b4b);\n"
"                border: 5px inset #FFF;\n"
"                box-shadow: none;\n"
"            }\n"
"            QPushButton::flat {\n"
"                border: none;\n"
"}")
        self.base_group_btns.setObjectName("base_group_btns")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.base_group_btns)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.base_group_btns_row1 = QtWidgets.QWidget(self.base_group_btns)
        self.base_group_btns_row1.setObjectName("base_group_btns_row1")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.base_group_btns_row1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.body_armours_btn = QtWidgets.QPushButton(self.base_group_btns_row1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.body_armours_btn.sizePolicy().hasHeightForWidth())
        self.body_armours_btn.setSizePolicy(sizePolicy)
        self.body_armours_btn.setStyleSheet("QPushButton {\n"
"                border: 1px solid #000;\n"
"                border-radius: 4px;\n"
"                background-color: qlineargradient(x1: 0, y1: 1, x2: 0, y2: 0, stop: 0 #1e1e1e, stop: 1 #3c3c3c);\n"
"                border-image: none;\n"
"              color: #FFF;\n"
"               box-shadow: inset 0 1px 1px #666, 0 1px 2px rgba(0,0,0,0.31);\n"
"                font-family: Open Sans;\n"
"                font-size: 12px;\n"
"               font-weight: bold;\n"
"               height: 36px;\n"
"                line-height: 36px;\n"
"                text-align: center;\n"
"                margin: 0px;\n"
"                padding: 5px 10px;\n"
"                cursor: pointer;\n"
"                text-shadow: 1px 1px #000;\n"
"                vertical-align: top;\n"
"           }\n"
"            QPushButton::hover {         \n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 rgba(30, 30, 30, 1), stop:1 rgba(75, 75, 75, 1));\n"
"           }\n"
"            QPushButton::pressed {\n"
"                \n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 rgba(221, 204, 153, 1), stop:1 rgba(255, 238, 187, 255));\n"
"            }\n"
"            QPushButton::checked {\n"
"                background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 rgba(221, 204, 153, 1), stop:1 rgba(255, 238, 187, 255));\n"
"                color: #332211;\n"
"text-shadow: 1px 1px #FFF;\n"
"box-shadow: inset 0 1px 1px #BBB, 0 1px 2px rgba(0,0,0,0.31);\n"
"font-weight: bold;\n"
"            }\n"
"            QPushButton::flat {\n"
"                border: none;\n"
"}")
        self.body_armours_btn.setCheckable(True)
        self.body_armours_btn.setObjectName("body_armours_btn")
        self.wizard_base_group_btns = QtWidgets.QButtonGroup(ItemOptionsWizard)
        self.wizard_base_group_btns.setObjectName("wizard_base_group_btns")
        self.wizard_base_group_btns.addButton(self.body_armours_btn)
        self.horizontalLayout_3.addWidget(self.body_armours_btn)
        self.boots_btn = QtWidgets.QPushButton(self.base_group_btns_row1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.boots_btn.sizePolicy().hasHeightForWidth())
        self.boots_btn.setSizePolicy(sizePolicy)
        self.boots_btn.setStyleSheet("QPushButton {\n"
"                border: 1px solid #000;\n"
"                border-radius: 4px;\n"
"                background-color: qlineargradient(x1: 0, y1: 1, x2: 0, y2: 0, stop: 0 #1e1e1e, stop: 1 #3c3c3c);\n"
"                border-image: none;\n"
"              color: #FFF;\n"
"               box-shadow: inset 0 1px 1px #666, 0 1px 2px rgba(0,0,0,0.31);\n"
"                font-family: Open Sans;\n"
"                font-size: 12px;\n"
"               font-weight: bold;\n"
"               height: 36px;\n"
"                line-height: 36px;\n"
"                text-align: center;\n"
"                margin: 0px;\n"
"                padding: 5px 10px;\n"
"                cursor: pointer;\n"
"                text-shadow: 1px 1px #000;\n"
"                vertical-align: top;\n"
"           }\n"
"            QPushButton::hover {         \n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 rgba(30, 30, 30, 1), stop:1 rgba(75, 75, 75, 1));\n"
"           }\n"
"            QPushButton::pressed {\n"
"                \n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 rgba(221, 204, 153, 1), stop:1 rgba(255, 238, 187, 255));\n"
"            }\n"
"            QPushButton::checked {\n"
"                background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 rgba(221, 204, 153, 1), stop:1 rgba(255, 238, 187, 255));\n"
"                color: #332211;\n"
"text-shadow: 1px 1px #FFF;\n"
"box-shadow: inset 0 1px 1px #BBB, 0 1px 2px rgba(0,0,0,0.31);\n"
"font-weight: bold;\n"
"            }\n"
"            QPushButton::flat {\n"
"                border: none;\n"
"}")
        self.boots_btn.setCheckable(True)
        self.boots_btn.setObjectName("boots_btn")
        self.wizard_base_group_btns.addButton(self.boots_btn)
        self.horizontalLayout_3.addWidget(self.boots_btn)
        self.helmets_btn = QtWidgets.QPushButton(self.base_group_btns_row1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.helmets_btn.sizePolicy().hasHeightForWidth())
        self.helmets_btn.setSizePolicy(sizePolicy)
        self.helmets_btn.setStyleSheet("QPushButton {\n"
"                border: 1px solid #000;\n"
"                border-radius: 4px;\n"
"                background-color: qlineargradient(x1: 0, y1: 1, x2: 0, y2: 0, stop: 0 #1e1e1e, stop: 1 #3c3c3c);\n"
"                border-image: none;\n"
"              color: #FFF;\n"
"               box-shadow: inset 0 1px 1px #666, 0 1px 2px rgba(0,0,0,0.31);\n"
"                font-family: Open Sans;\n"
"                font-size: 12px;\n"
"               font-weight: bold;\n"
"               height: 36px;\n"
"                line-height: 36px;\n"
"                text-align: center;\n"
"                margin: 0px;\n"
"                padding: 5px 10px;\n"
"                cursor: pointer;\n"
"                text-shadow: 1px 1px #000;\n"
"                vertical-align: top;\n"
"           }\n"
"            QPushButton::hover {         \n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 rgba(30, 30, 30, 1), stop:1 rgba(75, 75, 75, 1));\n"
"           }\n"
"            QPushButton::pressed {\n"
"                \n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 rgba(221, 204, 153, 1), stop:1 rgba(255, 238, 187, 255));\n"
"            }\n"
"            QPushButton::checked {\n"
"                background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 rgba(221, 204, 153, 1), stop:1 rgba(255, 238, 187, 255));\n"
"                color: #332211;\n"
"text-shadow: 1px 1px #FFF;\n"
"box-shadow: inset 0 1px 1px #BBB, 0 1px 2px rgba(0,0,0,0.31);\n"
"font-weight: bold;\n"
"            }\n"
"            QPushButton::flat {\n"
"                border: none;\n"
"}")
        self.helmets_btn.setCheckable(True)
        self.helmets_btn.setObjectName("helmets_btn")
        self.wizard_base_group_btns.addButton(self.helmets_btn)
        self.horizontalLayout_3.addWidget(self.helmets_btn)
        self.gloves_btn = QtWidgets.QPushButton(self.base_group_btns_row1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gloves_btn.sizePolicy().hasHeightForWidth())
        self.gloves_btn.setSizePolicy(sizePolicy)
        self.gloves_btn.setStyleSheet("QPushButton {\n"
"                border: 1px solid #000;\n"
"                border-radius: 4px;\n"
"                background-color: qlineargradient(x1: 0, y1: 1, x2: 0, y2: 0, stop: 0 #1e1e1e, stop: 1 #3c3c3c);\n"
"                border-image: none;\n"
"              color: #FFF;\n"
"               box-shadow: inset 0 1px 1px #666, 0 1px 2px rgba(0,0,0,0.31);\n"
"                font-family: Open Sans;\n"
"                font-size: 12px;\n"
"               font-weight: bold;\n"
"               height: 36px;\n"
"                line-height: 36px;\n"
"                text-align: center;\n"
"                margin: 0px;\n"
"                padding: 5px 10px;\n"
"                cursor: pointer;\n"
"                text-shadow: 1px 1px #000;\n"
"                vertical-align: top;\n"
"           }\n"
"            QPushButton::hover {         \n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 rgba(30, 30, 30, 1), stop:1 rgba(75, 75, 75, 1));\n"
"           }\n"
"            QPushButton::pressed {\n"
"                \n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 rgba(221, 204, 153, 1), stop:1 rgba(255, 238, 187, 255));\n"
"            }\n"
"            QPushButton::checked {\n"
"                background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 rgba(221, 204, 153, 1), stop:1 rgba(255, 238, 187, 255));\n"
"                color: #332211;\n"
"text-shadow: 1px 1px #FFF;\n"
"box-shadow: inset 0 1px 1px #BBB, 0 1px 2px rgba(0,0,0,0.31);\n"
"font-weight: bold;\n"
"            }\n"
"            QPushButton::flat {\n"
"                border: none;\n"
"}")
        self.gloves_btn.setCheckable(True)
        self.gloves_btn.setObjectName("gloves_btn")
        self.wizard_base_group_btns.addButton(self.gloves_btn)
        self.horizontalLayout_3.addWidget(self.gloves_btn)
        self.verticalLayout_5.addWidget(self.base_group_btns_row1)
        self.base_group_btns_row2 = QtWidgets.QWidget(self.base_group_btns)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.base_group_btns_row2.sizePolicy().hasHeightForWidth())
        self.base_group_btns_row2.setSizePolicy(sizePolicy)
        self.base_group_btns_row2.setObjectName("base_group_btns_row2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.base_group_btns_row2)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.one_handed_weapons_btn = QtWidgets.QPushButton(self.base_group_btns_row2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.one_handed_weapons_btn.sizePolicy().hasHeightForWidth())
        self.one_handed_weapons_btn.setSizePolicy(sizePolicy)
        self.one_handed_weapons_btn.setStyleSheet("QPushButton {\n"
"                border: 1px solid #000;\n"
"                border-radius: 4px;\n"
"                background-color: qlineargradient(x1: 0, y1: 1, x2: 0, y2: 0, stop: 0 #1e1e1e, stop: 1 #3c3c3c);\n"
"                border-image: none;\n"
"              color: #FFF;\n"
"               box-shadow: inset 0 1px 1px #666, 0 1px 2px rgba(0,0,0,0.31);\n"
"                font-family: Open Sans;\n"
"                font-size: 12px;\n"
"               font-weight: bold;\n"
"               height: 36px;\n"
"                line-height: 36px;\n"
"                text-align: center;\n"
"                margin: 0px;\n"
"                padding: 5px 10px;\n"
"                cursor: pointer;\n"
"                text-shadow: 1px 1px #000;\n"
"                vertical-align: top;\n"
"           }\n"
"            QPushButton::hover {         \n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 rgba(30, 30, 30, 1), stop:1 rgba(75, 75, 75, 1));\n"
"           }\n"
"            QPushButton::pressed {\n"
"                \n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 rgba(221, 204, 153, 1), stop:1 rgba(255, 238, 187, 255));\n"
"            }\n"
"            QPushButton::checked {\n"
"                background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 rgba(221, 204, 153, 1), stop:1 rgba(255, 238, 187, 255));\n"
"                color: #332211;\n"
"text-shadow: 1px 1px #FFF;\n"
"box-shadow: inset 0 1px 1px #BBB, 0 1px 2px rgba(0,0,0,0.31);\n"
"font-weight: bold;\n"
"            }\n"
"            QPushButton::flat {\n"
"                border: none;\n"
"}")
        self.one_handed_weapons_btn.setCheckable(True)
        self.one_handed_weapons_btn.setObjectName("one_handed_weapons_btn")
        self.wizard_base_group_btns.addButton(self.one_handed_weapons_btn)
        self.horizontalLayout_4.addWidget(self.one_handed_weapons_btn)
        self.two_handed_weapons_btn = QtWidgets.QPushButton(self.base_group_btns_row2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.two_handed_weapons_btn.sizePolicy().hasHeightForWidth())
        self.two_handed_weapons_btn.setSizePolicy(sizePolicy)
        self.two_handed_weapons_btn.setStyleSheet("QPushButton {\n"
"                border: 1px solid #000;\n"
"                border-radius: 4px;\n"
"                background-color: qlineargradient(x1: 0, y1: 1, x2: 0, y2: 0, stop: 0 #1e1e1e, stop: 1 #3c3c3c);\n"
"                border-image: none;\n"
"              color: #FFF;\n"
"               box-shadow: inset 0 1px 1px #666, 0 1px 2px rgba(0,0,0,0.31);\n"
"                font-family: Open Sans;\n"
"                font-size: 12px;\n"
"               font-weight: bold;\n"
"               height: 36px;\n"
"                line-height: 36px;\n"
"                text-align: center;\n"
"                margin: 0px;\n"
"                padding: 5px 10px;\n"
"                cursor: pointer;\n"
"                text-shadow: 1px 1px #000;\n"
"                vertical-align: top;\n"
"           }\n"
"            QPushButton::hover {         \n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 rgba(30, 30, 30, 1), stop:1 rgba(75, 75, 75, 1));\n"
"           }\n"
"            QPushButton::pressed {\n"
"                \n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 rgba(221, 204, 153, 1), stop:1 rgba(255, 238, 187, 255));\n"
"            }\n"
"            QPushButton::checked {\n"
"                background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 rgba(221, 204, 153, 1), stop:1 rgba(255, 238, 187, 255));\n"
"                color: #332211;\n"
"text-shadow: 1px 1px #FFF;\n"
"box-shadow: inset 0 1px 1px #BBB, 0 1px 2px rgba(0,0,0,0.31);\n"
"font-weight: bold;\n"
"            }\n"
"            QPushButton::flat {\n"
"                border: none;\n"
"}")
        self.two_handed_weapons_btn.setCheckable(True)
        self.two_handed_weapons_btn.setObjectName("two_handed_weapons_btn")
        self.wizard_base_group_btns.addButton(self.two_handed_weapons_btn)
        self.horizontalLayout_4.addWidget(self.two_handed_weapons_btn)
        self.offhands_btn = QtWidgets.QPushButton(self.base_group_btns_row2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.offhands_btn.sizePolicy().hasHeightForWidth())
        self.offhands_btn.setSizePolicy(sizePolicy)
        self.offhands_btn.setStyleSheet("QPushButton {\n"
"                border: 1px solid #000;\n"
"                border-radius: 4px;\n"
"                background-color: qlineargradient(x1: 0, y1: 1, x2: 0, y2: 0, stop: 0 #1e1e1e, stop: 1 #3c3c3c);\n"
"                border-image: none;\n"
"              color: #FFF;\n"
"               box-shadow: inset 0 1px 1px #666, 0 1px 2px rgba(0,0,0,0.31);\n"
"                font-family: Open Sans;\n"
"                font-size: 12px;\n"
"               font-weight: bold;\n"
"               height: 36px;\n"
"                line-height: 36px;\n"
"                text-align: center;\n"
"                margin: 0px;\n"
"                padding: 5px 10px;\n"
"                cursor: pointer;\n"
"                text-shadow: 1px 1px #000;\n"
"                vertical-align: top;\n"
"           }\n"
"            QPushButton::hover {         \n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 rgba(30, 30, 30, 1), stop:1 rgba(75, 75, 75, 1));\n"
"           }\n"
"            QPushButton::pressed {\n"
"                \n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 rgba(221, 204, 153, 1), stop:1 rgba(255, 238, 187, 255));\n"
"            }\n"
"            QPushButton::checked {\n"
"                background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 rgba(221, 204, 153, 1), stop:1 rgba(255, 238, 187, 255));\n"
"                color: #332211;\n"
"text-shadow: 1px 1px #FFF;\n"
"box-shadow: inset 0 1px 1px #BBB, 0 1px 2px rgba(0,0,0,0.31);\n"
"font-weight: bold;\n"
"            }\n"
"            QPushButton::flat {\n"
"                border: none;\n"
"}")
        self.offhands_btn.setCheckable(True)
        self.offhands_btn.setObjectName("offhands_btn")
        self.wizard_base_group_btns.addButton(self.offhands_btn)
        self.horizontalLayout_4.addWidget(self.offhands_btn)
        self.verticalLayout_5.addWidget(self.base_group_btns_row2, 0, QtCore.Qt.AlignHCenter)
        self.base_group_btns_row3 = QtWidgets.QWidget(self.base_group_btns)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.base_group_btns_row3.sizePolicy().hasHeightForWidth())
        self.base_group_btns_row3.setSizePolicy(sizePolicy)
        self.base_group_btns_row3.setObjectName("base_group_btns_row3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.base_group_btns_row3)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.jewellery_btn = QtWidgets.QPushButton(self.base_group_btns_row3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.jewellery_btn.sizePolicy().hasHeightForWidth())
        self.jewellery_btn.setSizePolicy(sizePolicy)
        self.jewellery_btn.setStyleSheet("QPushButton {\n"
"                border: 1px solid #000;\n"
"                border-radius: 4px;\n"
"                background-color: qlineargradient(x1: 0, y1: 1, x2: 0, y2: 0, stop: 0 #1e1e1e, stop: 1 #3c3c3c);\n"
"                border-image: none;\n"
"              color: #FFF;\n"
"               box-shadow: inset 0 1px 1px #666, 0 1px 2px rgba(0,0,0,0.31);\n"
"                font-family: Open Sans;\n"
"                font-size: 12px;\n"
"               font-weight: bold;\n"
"               height: 36px;\n"
"                line-height: 36px;\n"
"                text-align: center;\n"
"                margin: 0px;\n"
"                padding: 5px 10px;\n"
"                cursor: pointer;\n"
"                text-shadow: 1px 1px #000;\n"
"                vertical-align: top;\n"
"           }\n"
"            QPushButton::hover {         \n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 rgba(30, 30, 30, 1), stop:1 rgba(75, 75, 75, 1));\n"
"           }\n"
"            QPushButton::pressed {\n"
"                \n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 rgba(221, 204, 153, 1), stop:1 rgba(255, 238, 187, 255));\n"
"            }\n"
"            QPushButton::checked {\n"
"                background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 rgba(221, 204, 153, 1), stop:1 rgba(255, 238, 187, 255));\n"
"                color: #332211;\n"
"text-shadow: 1px 1px #FFF;\n"
"box-shadow: inset 0 1px 1px #BBB, 0 1px 2px rgba(0,0,0,0.31);\n"
"font-weight: bold;\n"
"            }\n"
"            QPushButton::flat {\n"
"                border: none;\n"
"}")
        self.jewellery_btn.setCheckable(True)
        self.jewellery_btn.setObjectName("jewellery_btn")
        self.wizard_base_group_btns.addButton(self.jewellery_btn)
        self.horizontalLayout_2.addWidget(self.jewellery_btn)
        self.jewels_btn = QtWidgets.QPushButton(self.base_group_btns_row3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.jewels_btn.sizePolicy().hasHeightForWidth())
        self.jewels_btn.setSizePolicy(sizePolicy)
        self.jewels_btn.setStyleSheet("QPushButton {\n"
"                border: 1px solid #000;\n"
"                border-radius: 4px;\n"
"                background-color: qlineargradient(x1: 0, y1: 1, x2: 0, y2: 0, stop: 0 #1e1e1e, stop: 1 #3c3c3c);\n"
"                border-image: none;\n"
"              color: #FFF;\n"
"               box-shadow: inset 0 1px 1px #666, 0 1px 2px rgba(0,0,0,0.31);\n"
"                font-family: Open Sans;\n"
"                font-size: 12px;\n"
"               font-weight: bold;\n"
"               height: 36px;\n"
"                line-height: 36px;\n"
"                text-align: center;\n"
"                margin: 0px;\n"
"                padding: 5px 10px;\n"
"                cursor: pointer;\n"
"                text-shadow: 1px 1px #000;\n"
"                vertical-align: top;\n"
"           }\n"
"            QPushButton::hover {         \n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 rgba(30, 30, 30, 1), stop:1 rgba(75, 75, 75, 1));\n"
"           }\n"
"            QPushButton::pressed {\n"
"                \n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 rgba(221, 204, 153, 1), stop:1 rgba(255, 238, 187, 255));\n"
"            }\n"
"            QPushButton::checked {\n"
"                background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 rgba(221, 204, 153, 1), stop:1 rgba(255, 238, 187, 255));\n"
"                color: #332211;\n"
"text-shadow: 1px 1px #FFF;\n"
"box-shadow: inset 0 1px 1px #BBB, 0 1px 2px rgba(0,0,0,0.31);\n"
"font-weight: bold;\n"
"            }\n"
"            QPushButton::flat {\n"
"                border: none;\n"
"}")
        self.jewels_btn.setCheckable(True)
        self.jewels_btn.setChecked(False)
        self.jewels_btn.setObjectName("jewels_btn")
        self.wizard_base_group_btns.addButton(self.jewels_btn)
        self.horizontalLayout_2.addWidget(self.jewels_btn)
        self.cluster_jewels_btn = QtWidgets.QPushButton(self.base_group_btns_row3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cluster_jewels_btn.sizePolicy().hasHeightForWidth())
        self.cluster_jewels_btn.setSizePolicy(sizePolicy)
        self.cluster_jewels_btn.setStyleSheet("QPushButton {\n"
"                border: 1px solid #000;\n"
"                border-radius: 4px;\n"
"                background-color: qlineargradient(x1: 0, y1: 1, x2: 0, y2: 0, stop: 0 #1e1e1e, stop: 1 #3c3c3c);\n"
"                border-image: none;\n"
"              color: #FFF;\n"
"               box-shadow: inset 0 1px 1px #666, 0 1px 2px rgba(0,0,0,0.31);\n"
"                font-family: Open Sans;\n"
"                font-size: 12px;\n"
"               font-weight: bold;\n"
"               height: 36px;\n"
"                line-height: 36px;\n"
"                text-align: center;\n"
"                margin: 0px;\n"
"                padding: 5px 10px;\n"
"                cursor: pointer;\n"
"                text-shadow: 1px 1px #000;\n"
"                vertical-align: top;\n"
"           }\n"
"            QPushButton::hover {         \n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 rgba(30, 30, 30, 1), stop:1 rgba(75, 75, 75, 1));\n"
"           }\n"
"            QPushButton::pressed {\n"
"                \n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 rgba(221, 204, 153, 1), stop:1 rgba(255, 238, 187, 255));\n"
"            }\n"
"            QPushButton::checked {\n"
"                background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 rgba(221, 204, 153, 1), stop:1 rgba(255, 238, 187, 255));\n"
"                color: #332211;\n"
"text-shadow: 1px 1px #FFF;\n"
"box-shadow: inset 0 1px 1px #BBB, 0 1px 2px rgba(0,0,0,0.31);\n"
"font-weight: bold;\n"
"            }\n"
"            QPushButton::flat {\n"
"                border: none;\n"
"}")
        self.cluster_jewels_btn.setCheckable(True)
        self.cluster_jewels_btn.setObjectName("cluster_jewels_btn")
        self.wizard_base_group_btns.addButton(self.cluster_jewels_btn)
        self.horizontalLayout_2.addWidget(self.cluster_jewels_btn)
        self.flasks_btn = QtWidgets.QPushButton(self.base_group_btns_row3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.flasks_btn.sizePolicy().hasHeightForWidth())
        self.flasks_btn.setSizePolicy(sizePolicy)
        self.flasks_btn.setStyleSheet("QPushButton {\n"
"                border: 1px solid #000;\n"
"                border-radius: 4px;\n"
"                background-color: qlineargradient(x1: 0, y1: 1, x2: 0, y2: 0, stop: 0 #1e1e1e, stop: 1 #3c3c3c);\n"
"                border-image: none;\n"
"              color: #FFF;\n"
"               box-shadow: inset 0 1px 1px #666, 0 1px 2px rgba(0,0,0,0.31);\n"
"                font-family: Open Sans;\n"
"                font-size: 12px;\n"
"               font-weight: bold;\n"
"               height: 36px;\n"
"                line-height: 36px;\n"
"                text-align: center;\n"
"                margin: 0px;\n"
"                padding: 5px 10px;\n"
"                cursor: pointer;\n"
"                text-shadow: 1px 1px #000;\n"
"                vertical-align: top;\n"
"           }\n"
"            QPushButton::hover {         \n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 rgba(30, 30, 30, 1), stop:1 rgba(75, 75, 75, 1));\n"
"           }\n"
"            QPushButton::pressed {\n"
"                \n"
"    background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 rgba(221, 204, 153, 1), stop:1 rgba(255, 238, 187, 255));\n"
"            }\n"
"            QPushButton::checked {\n"
"                background-color: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 rgba(221, 204, 153, 1), stop:1 rgba(255, 238, 187, 255));\n"
"                color: #332211;\n"
"text-shadow: 1px 1px #FFF;\n"
"box-shadow: inset 0 1px 1px #BBB, 0 1px 2px rgba(0,0,0,0.31);\n"
"font-weight: bold;\n"
"            }\n"
"            QPushButton::flat {\n"
"                border: none;\n"
"}")
        self.flasks_btn.setCheckable(True)
        self.flasks_btn.setObjectName("flasks_btn")
        self.wizard_base_group_btns.addButton(self.flasks_btn)
        self.horizontalLayout_2.addWidget(self.flasks_btn)
        self.verticalLayout_5.addWidget(self.base_group_btns_row3)
        self.verticalLayout_4.addWidget(self.base_group_btns, 0, QtCore.Qt.AlignHCenter)
        ItemOptionsWizard.addPage(self.wizard_base_groups_page)
        self.wizard_base_selection_page = QtWidgets.QWizardPage()
        self.wizard_base_selection_page.setObjectName("wizard_base_selection_page")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.wizard_base_selection_page)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.base_selection_page = BaseSelection(self.wizard_base_selection_page)
        self.base_selection_page.setObjectName("base_selection_page")
        self.verticalLayout_6.addWidget(self.base_selection_page)
        ItemOptionsWizard.addPage(self.wizard_base_selection_page)
        self.wizard_item_selection_page = QtWidgets.QWizardPage()
        self.wizard_item_selection_page.setObjectName("wizard_item_selection_page")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.wizard_item_selection_page)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.item_selection_page = ItemSelection(self.wizard_item_selection_page)
        self.item_selection_page.setObjectName("item_selection_page")
        self.verticalLayout_7.addWidget(self.item_selection_page)
        ItemOptionsWizard.addPage(self.wizard_item_selection_page)
        self.wizard_item_options_page = QtWidgets.QWizardPage()
        self.wizard_item_options_page.setObjectName("wizard_item_options_page")
        ItemOptionsWizard.addPage(self.wizard_item_options_page)
        self.wizard_confirm_options_page = QtWidgets.QWizardPage()
        self.wizard_confirm_options_page.setObjectName("wizard_confirm_options_page")
        ItemOptionsWizard.addPage(self.wizard_confirm_options_page)
        self.project_name_label.setBuddy(self.project_name_input)

        self.retranslateUi(ItemOptionsWizard)
        QtCore.QMetaObject.connectSlotsByName(ItemOptionsWizard)

    def retranslateUi(self, ItemOptionsWizard):
        _translate = QtCore.QCoreApplication.translate
        ItemOptionsWizard.setWindowTitle(_translate("ItemOptionsWizard", "Item Options"))
        self.wizard_start_page.setTitle(_translate("ItemOptionsWizard", "Start a Crafting Project"))
        self.wizard_start_page.setSubTitle(_translate("ItemOptionsWizard", "Start a new crafting project with the name of your choice"))
        self.project_name_label.setText(_translate("ItemOptionsWizard", "Project Name:"))
        self.project_name_input.setPlaceholderText(_translate("ItemOptionsWizard", "Type name of the project here"))
        self.wizard_base_groups_page.setTitle(_translate("ItemOptionsWizard", "Select A Base Group"))
        self.body_armours_btn.setText(_translate("ItemOptionsWizard", "Body Armours"))
        self.boots_btn.setText(_translate("ItemOptionsWizard", "Boots"))
        self.helmets_btn.setText(_translate("ItemOptionsWizard", "Helmets"))
        self.gloves_btn.setText(_translate("ItemOptionsWizard", "Gloves"))
        self.one_handed_weapons_btn.setText(_translate("ItemOptionsWizard", "One Handed Weapons"))
        self.two_handed_weapons_btn.setText(_translate("ItemOptionsWizard", "Two Handed Weapons"))
        self.offhands_btn.setText(_translate("ItemOptionsWizard", "Offhands"))
        self.jewellery_btn.setText(_translate("ItemOptionsWizard", "Jewellery"))
        self.jewels_btn.setText(_translate("ItemOptionsWizard", "Jewels"))
        self.cluster_jewels_btn.setText(_translate("ItemOptionsWizard", "Cluster Jewels"))
        self.flasks_btn.setText(_translate("ItemOptionsWizard", "Flasks"))
from ..pages.base_selection import BaseSelection
from ..pages.item_selection import ItemSelection
from .. import assets_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ItemOptionsWizard = QtWidgets.QWizard()
    ui = Ui_ItemOptionsWizard()
    ui.setupUi(ItemOptionsWizard)
    ItemOptionsWizard.show()
    sys.exit(app.exec_())
