ITEM_CLASS_WHITELIST = {
    "LifeFlask",
    "ManaFlask",
    "HybridFlask",
    "Amulet",
    "Ring",
    "Claw",
    "Dagger",
    "Rune Dagger",
    "Wand",
    "One Hand Sword",
    "Thrusting One Hand Sword",
    "One Hand Axe",
    "One Hand Mace",
    "Bow",
    "Staff",
    "Warstaff",
    "Two Hand Sword",
    "Two Hand Axe",
    "Two Hand Mace",
    "Quiver",
    "Belt",
    "Gloves",
    "Boots",
    "Body Armour",
    "Helmet",
    "Shield",
    "Sceptre",
    "UtilityFlask",
    "UtilityFlaskCritical",
    "Jewel",
    "AbyssJewel",

}

ITEM_CLASS_BLACKLIST = {
    "LabyrinthTrinket",
    "MiscMapItem",
    "Leaguestone",
    "LabyrinthItem",
    "PantheonSoul",
    "UniqueFragment",
    "IncursionItem",
    "MetamorphosisDNA",
    "HideoutDoodad",
    "LabyrinthMapItem",
    "Incubator",
    "Microtransaction",
    "HarvestInfrastructure",
    "HarvestSeed",
    "HarvestPlantBooster",
    "Trinket",
    "HeistObjective",
    "HiddenItem",
    "ArchnemesisMod",
    "MemoryLine",
    "HeistContract",
    "HeistBlueprint",
    "HeistEquipmentWeapon",
    "HeistEquipmentTool",
    "HeistEquipmentUtility",
    "HeistEquipmentReward",
    "DivinationCard",
    "Map",
    "MapFragment",
    "AtlasRegionUpgradeItem",
    "ExpeditionLogbook",
    "IncubatorStackable",
    "AtlasUpgradeItem",
    "SentinelDrone",
    "DelveStackableSocketableCurrency",
    "DelveSocketableCurrency",
    "QuestItem",
    "StackableCurrency",
    "Active Skill Gem",
    "Support Skill Gem",
    "Currency",
    "FishingRod",
}

BASE_ITEM_BLACKLIST = {
    'Breach Ring',
    'Ring',
    'Shadowed Ring',
    'Tenebrous Ring',
    'Gloam Ring',
    'Penumbra Ring',
    'Dusk Ring',
    'Unset Amulet',

}
TAGS_MAP = {
    'Body Armour': {
        "Body Armour (dex)": ["armour", "dex_armour"],
        "Body Armour (dex/int)": ["armour", "dex_int_armour"],
        "Body Armour (dex/str)": ["armour", "dex_str_armour"],
        "Body Armour (dex/str/int)": ["armour", "dex_str_int_armour"],
        "Body Armour (str)": ["armour", "str_armour"],
        "Body Armour (str/int)": ["armour", "str_int_armour"],
        "Body Armour (int)": ["armour", "int_armour"],
    },
    'Boots': {
        "Boots (dex)": ["armour", "dex_armour"],
        "Boots (dex/int)": ["armour", "dex_int_armour"],
        "Boots (dex/str)": ["armour", "dex_str_armour"],
        "Boots (dex/str/int)": ["armour", "dex_str_int_armour"],
        "Boots (str)": ["armour", "str_armour"],
        "Boots (str/int)": ["armour", "str_int_armour"],
        "Boots (int)": ["armour", "int_armour"],
    },
}

ITEM_CLASS_SUBTYPES = {
    'Body Armour': {"dex_armour", "dex_int_armour", "int_armour", "str_armour", "str_dex_armour",
                    "str_dex_int_armour", "str_int_armour"},
    'Boots': {"ward_armour", "dex_armour", "dex_int_armour", "int_armour", "str_armour", "str_dex_armour",
              "str_int_armour"},
    'Gloves': {"ward_armour", "dex_armour", "dex_int_armour", "int_armour", "str_armour", "str_dex_armour",
               "str_int_armour"},
    'Helmet': {"ward_armour", "dex_armour", "dex_int_armour", "int_armour", "str_armour", "str_dex_armour",
               "str_int_armour"},
    'Shield': {"dex_armour", "dex_int_armour", "int_armour", "str_armour", "str_dex_armour", "str_int_armour"},
    'Jewellery': {"amulet", "belt", "ring"},
    'One Handed Weapons': {"claw", "attack_dagger", "dagger", "axe", "mace",
                           "sword", "sceptre", "rapier", "wand"},
    'Two Handed Weapons': {"bow", "staff", "two_hand_axe", "two_hand_sword", "warstaff", "two_hand_mace"},
    'Offhands': {"quiver"},
    'Jewels': {"abyss_jewel", "jewel"},
    'Flasks': {"hybrid_flask", "life_flask", "mana_flask", "utility_flask"}
}

SUBTYPE_DISPLAY_NAMES = {
    "abyss_jewel": "Abyss Jewel",
    "jewel": "Jewel",
    "focus_can_roll_minion_modifiers": "Bone Spirit Shield",
    "claw": "Claw",
    "weapon_can_roll_minion_modifiers": "Convoking Wand",
    "attack_dagger": "Dagger",
    "dagger": "Rune Dagger",
    "axe": "One Hand Axe",
    "mace": "One Hand Mace",
    "sword": "One Hand Sword",
    "sceptre": "Sceptre",
    "rapier": "Thrusting One Hand Sword",
    "wand": "Wand",
    "armour": "{}",
    "bow": "Bow",
    "staff": "Staff",
    "warstaff": "Warstaff",
    "two_hand_axe": "Two Hand Axe",
    "two_hand_sword": "Two Hand Sword",
    "two_hand_mace": "Two Hand Mace",
    "ward_armour": "{}(Ward)",
    "dex_armour": "{}(dex)",
    "dex_int_armour": "{}(dex/int)",
    "int_armour": "{}(int)",
    "str_armour": "{}(str)",
    "str_dex_armour": "{}(str/dex)",
    "str_dex_int_armour": "{}(str/dex/int)",
    "str_int_armour": "{}(str/int)",
    "amulet": 'Amulet',
    "life_flask": "Life Flask",
    "mana_flask": "Mana Flask",
    "hybrid_flask": "Hybrid Flask",
    "utility_flask": "Utility Flask",
    "ring": "Ring",
    "belt": "Belt",
    "abyss_jewel_ranged": "Searching Eye Jewel",
    "abyss_jewel_caster": "Hypnotic Eye Jewel",
    "abyss_jewel_summoner": "Ghastly Eye Jewel",
    "abyss_jewel_melee": "Murderous Eye Jewel",
    "dexjewel": "Viridian Jewel",
    "intjewel": "Cobalt Jewel",
    "strjewel": "Crimson Jewel",
    "shield": "Shield",
    "quiver": "Quiver",
    "expansion_jewel_small": "Small Cluster Jewel",
    "expansion_jewel_medium": "Medium Cluster Jewel",
    "expansion_jewel_large": "Large Cluster Jewel",
    "helmet": "Helmet"
}

REVERSED_SUBTYPE_DISPLAY_NAMES = {v.format(k) if '{}' in v else v: k for k, v in SUBTYPE_DISPLAY_NAMES.items()}

ALL_SUBTYPES = {"armour", "dex_armour", "dex_int_armour", "int_armour", "str_armour", "str_dex_armour",
                "str_dex_int_armour", "str_int_armour"
                }

SUBTYPE_TAGS_MAP = {"(dex)": "dex_armour",
                    "(dex/int)": "dex_int_armour",
                    "(int)": "int_armour",
                    "(str)": "str_armour",
                    "(str/dex)": "str_dex_armour",
                    "(str/dex/int)": "str_dex_int_armour",
                    "(str/int)": "str_int_armour",
                    "(Ward)": "ward_armour"
                    }
